import type { CapacitorConfig } from "@capacitor/cli";

const config: CapacitorConfig = {
  appId: "com.hashhustle.app",
  appName: "HashHustle",
  webDir: "dist/client",

  // Android platform basics.
  android: {
    // The web app talks to its backend over HTTPS only (server functions run on
    // the deployed origin). Mixed content stays locked down.
    allowMixedContent: false,
  },

  // ---------------------------------------------------------------------------
  // Two ways the Android shell can load the app:
  //
  // 1) BUNDLED (default): `npm run cap:sync` copies `dist/client/` into the APK
  //    (android/app/src/main/assets/public). The static shell (index.html) is
  //    generated by scripts/gen-cap-html.mjs. Client-side UI renders offline,
  //    but mining/balance calls need a reachable backend.
  //
  // 2) REMOTE (recommended for real IAP): uncomment `server.url` and point it at
  //    the deployed HashHustle origin. The WebView then loads the full SSR app
  //    with its backend, and Play Billing entitlements can be verified
  //    server-side. Requires INTERNET permission (already in the manifest).
  //
  // server: {
  //   url: "https://<deployed-hashhustle-origin>",
  //   cleartext: false,
  // },
  // ---------------------------------------------------------------------------
};

export default config;
